###########################
# Local Makefile settings #
###########################
INCFILES  = 
OBJFILES  = 
LIBFILE   =
BINFILES  =
SCRIPTS   =
DATAFILES =
LIBS      =
SUBDIRS   = gbpCosmo gbpSPH gbpHalos gbpTrees gbpClustering
#############################
