#!/bin/bash

echo
if [ "$#" == "0" ];
then
  echo " Syntax: "$0" command [optional arguments]"
  echo " ------"
  echo
  echo "   where commands can be :"
  echo
  gbpCode_new --help
  gbpCode_add --help
  echo
  exit 1
fi

if [ "$1" == 'new' ];
then
   gbpCode_new ${@:2}
elif [ "$1" == 'add' ];
then
   gbpCode_add ${@:2}
else
   echo "Unknown command {"$1"}".
fi

