#!/bin/bash

echo
if [ "$#" == "0" ];
then
  echo " Syntax: "$0" command [optional arguments]"
  echo " ------"
  echo
  echo "   where commands can be :"
  echo
  gbpDir_push --help
  gbpDir_pull --help
  gbpDir_list --help
  gbpDir_item --help
  echo
  exit 1
fi

if [ "$1" == 'push' ];
then
   gbpDir_push ${@:2}
elif [ "$1" == 'pull' ];
then
   gbpDir_pull ${@:2}
elif [ "$1" == 'list' ];
then
   gbpDir_list ${@:2}
elif [ "$1" == 'item' ];
then
   gbpDir_item ${@:2}
else
   echo "Unknown command {"$1"}".
fi

