#!/bin/bash

if [ "$1" == "--help" ];
then
  echo "      list - List directories in the stack."
  exit 0
fi

FILENAME=$HOME"/.gbpDir.txt"

count=0
if [[ -f $FILENAME ]];
  then
  DIRS=`cat $FILENAME`
  for DIR_I in $DIRS
  do
    count=$(($count + 1))
    echo $count') '$DIR_I
  done
else
  echo 'Stack file is empty'
fi


