#############################
# Library-specific settings #
#############################
INCFILES  = 
OBJFILES  = ran1.o
LIBFILE   = libgbpUtils.a
BINFILES  = create_tmpfile gpause random_numbers
LIBS      = -lgbpUtils
SCRIPTS   = run_mpi
#############################
