#!/bin/csh -f

if ($#argv < 1) then
  echo
  echo 'Syntax: run_valgrind executable args'
  echo '------'
  echo
  exit(1)
else
  set ARG_CMD=($argv[1])
endif 

# Build command string
set CMD_STRING="valgrind --leak-check=yes --show-reachable=yes "$ARG_CMD
@ i=2
while ($i <= $#argv)
  set set CMD_STRING=(${CMD_STRING} $argv[$i])
  @ i++
end

# Execute command string
$CMD_STRING

