#############################
# Library-specific settings #
#############################
INCFILES  = gbpParse.h 
LIBFILE   = 
OBJFILES  =
LIBS      = 
SUBDIRS   = core parameter_files
BINFILES  = 
SCRIPTS   = 
#############################
