#############################
# Library-specific settings #
#############################
INCFILES  = gbpFITS.h
OBJFILES  = transpose_array.o  \
	    read_image_FITS.o  \
	    write_image_FITS.o
LIBFILE   = 
BINFILES  = 
LIBS      = 
SUBDIRS   =
#############################
