###########################
# Local Makefile settings #
###########################
INCFILES  = 
OBJFILES  = 
LIBFILE   =
BINFILES  =
SCRIPTS   =
DATAFILES =
LIBS      =
SUBDIRS   = gbpCosmo gbpSims
ifeq ($(USE_FFTW),1)
  SUBDIRS := $(SUBDIRS) gbpClustering gbpSims_Swap_Endian
endif
#############################
