#############################
# Library-specific settings #
#############################
INCFILES  = gbpSSimPL.h
OBJFILES  = swap_endian_snapshot.o \
	        swap_endian_smooth.o   \
	        swap_endian_grids.o    \
	        swap_endian_halos.o    \
	        swap_endian_catalogs.o
LIBFILE   = libgbpSSimPL.a
BINFILES  = swap_endian_SSimPL
LIBS      = -lgbpSSimPL -lgbpHalos -lgbpSPH -lgbpCosmo -lgbpMath -lgbpLib
#############################
