#############################
# Library-specific settings #
#############################
INCFILES = gbpRNG.h 
OBJFILES = init_RNG.o                     \
           free_RNG.o                     \
           random_number.o                \
	   random_lognormal.o             \
	   init_seed_from_clock.o         \
           random_gaussian.o
LIBFILE  = 
BINFILES = 
LIBS     = 
SUBDIRS  = 
#############################
USE_SPRNG=1
