###########################
# Local Makefile settings #
###########################
INCFILES  = 
OBJFILES  = 
LIBFILE   =
BINFILES  =
SCRIPTS   =
DATAFILES =
LIBS      =
SUBDIRS   = gbpSPH gbpHalos gbpTrees 
ifeq ($(USE_GDLIB),1)
  SUBDIRS := $(SUBDIRS) gbpRender
endif
#############################
