#############################
# Library-specific settings #
#############################
INCFILES = gbpStats.h 
OBJFILES = calc_median.o         
LIBFILE  =
BINFILES = 
LIBS     = 
SUBDIRS  = 
#############################
