#############################
# Library-specific settings #
#############################
INCFILES = gbpStats.h 
OBJFILES = calc_sep_periodic.o   \
	   calc_median.o         
LIBFILE  =
BINFILES = 
LIBS     = 
SUBDIRS  = 
#############################
