#############################
# Library-specific settings #
#############################
INCFILES = gbpStats.h 
OBJFILES = calc_median.o        \
	   calc_sep_periodic.o 
LIBFILE  =
BINFILES = 
LIBS     = 
SUBDIRS  = 
#############################
