#############################
# Library-specific settings #
#############################
INCFILES  = gbpLib.h
LIBFILE   = libgbpLib.a
OBJFILES  = 
BINFILES  =
LIBS      =
SUBDIRS   = gbpCommon gbpSID gbpParse gbpADaPS gbpMultifile
ifeq ($(USE_CFITSIO),1)
  SUBDIRS := $(SUBDIRS) gbpFITS
endif
ifeq ($(USE_HDF5),1)
  SUBDIRS := $(SUBDIRS) gbpHDF5
endif
#############################

