#############################
# Library-specific settings #
#############################
INCFILES  = gbpSort.h
OBJFILES  = sort.o       \
            heap_sort.o  \
	    merge_sort.o 
LIBFILE   = 
BINFILES  = 
LIBS      = 
SUBDIRS   =
#############################
