#############################
# Library-specific settings #
#############################
INCFILES  = gbpSort.h
OBJFILES  = heap_sort.o  \
	    merge_sort.o \
	    sort.o
LIBFILE   = 
BINFILES  = 
LIBS      = 
SUBDIRS   =
#############################
